# Generated by Django 4.2 on 2023-04-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
