# Generated by Django 4.2 on 2023-04-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oceans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('square', models.FloatField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Океан',
                'verbose_name_plural': 'Океаны',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='climate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='coat_of_arms',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='country',
            name='internal_division',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='official_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='square',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Rivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('river_length', models.FloatField(max_length=5)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.region')),
            ],
            options={
                'verbose_name': 'Река',
                'verbose_name_plural': 'Реки',
            },
        ),
        migrations.CreateModel(
            name='Mountains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('mountain_height', models.FloatField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.region')),
            ],
            options={
                'verbose_name': 'Гора',
                'verbose_name_plural': 'Горы',
            },
        ),
    ]
