# Generated by Django 4.2 on 2023-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0005_country_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oceans',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
